# Generated by Django 5.1 on 2024-09-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='inventory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
