# Generated by Django 5.1 on 2024-08-24 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(upload_to='media/')),
                ('strength', models.IntegerField()),
                ('resistence', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('luck', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('bio', models.TextField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.race')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.region')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('FR', 'Friendly'), ('E', 'Enemy'), ('N', 'Neutral'), ('L', 'Love'), ('A', 'Acquaintance'), ('F', 'Family')], default='N', max_length=2)),
                ('character_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation1', to='character.character')),
                ('character_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation2', to='character.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='relation',
            field=models.ManyToManyField(to='character.relation'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(to='character.skill'),
        ),
    ]
