# Generated by Django 5.1 on 2024-08-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='relation',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
