# Generated by Django 5.1 on 2024-08-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_remove_character_relation_delete_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(),
        ),
    ]
