# Generated by Django 5.1 on 2024-09-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_region_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='element',
            new_name='school',
        ),
    ]
