# Generated by Django 5.1 on 2024-09-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_rename_element_skill_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(),
        ),
    ]
