# Generated by Django 5.1 on 2024-09-13 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_alter_race_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.race'),
        ),
        migrations.AlterField(
            model_name='character',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.region'),
        ),
    ]
