# Generated by Django 5.1 on 2024-09-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_character_race_alter_character_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
