# Generated by Django 5.1 on 2024-09-13 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0006_alter_character_race_alter_character_region'),
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('reward', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('duration', models.DurationField()),
                ('deadline', models.DurationField()),
                ('client', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('monster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monster.monster')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.region')),
            ],
        ),
    ]
