# Generated by Django 5.1 on 2024-09-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
