# Generated by Django 5.1 on 2024-09-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_mission_deadline_alter_mission_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='rank',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('Unknown', 'Unknown')], default='Unknown', max_length=7, null=True),
        ),
    ]
