# Generated by Django 5.1 on 2024-10-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_mission_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='notes',
            field=models.TextField(),
        ),
    ]
